Use testpwa;

INSERT INTO albums (nomAlbum) VALUES ('Korn');
INSERT INTO albums (nomAlbum) VALUES ('Life Is Peachy');
INSERT INTO albums (nomAlbum) VALUES ('Follow The Leader');
INSERT INTO albums (nomAlbum) VALUES ('Issues');
INSERT INTO albums (nomAlbum) VALUES ('Untouchables');
INSERT INTO albums (nomAlbum) VALUES ('Take a Look In The Mirror');
INSERT INTO albums (nomAlbum) VALUES ('See You On THe Other Side');
INSERT INTO albums (nomAlbum) VALUES ('Sans Titre');
INSERT INTO albums (nomAlbum) VALUES ('Korn III: Remember Who You Are');
INSERT INTO albums (nomAlbum) VALUES ('The Path Of Totality');
INSERT INTO albums (nomAlbum) VALUES ('The Paradigm Shift');
INSERT INTO albums (nomAlbum) VALUES ('The Serenity Of Suffering');
INSERT INTO albums (nomAlbum) VALUES ('The Nothing');

INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Blind', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Ball Tongue', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Need To', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Clown', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Divine', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Faget', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Shoots and Ladders', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Predictable', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Fake', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Lies', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Helmet in the Bush', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Daddy', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Michael and Geri', '1');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Twist', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Chi', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Lost', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Swallow', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Porno Creep', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Good God', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Mr Rogers', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Kunt', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('No Place To Hide', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Wicked', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('A.D.I.D.A.S', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Low Rider', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Ass Itch', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Kill You', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Twist', '2');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("It's On!", '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Freak On a Leash', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Got The Life', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Dead Body Everywhere', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Children Of The Korn', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('B.B.K', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Pretty', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('All In The Family', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Reclaim My Place', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Justin', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Seed', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Cameltosis', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('My Gift To You', '3');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Dead', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Falling Away From Me', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Trash', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('4 U', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Beg For Me', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Make Me Bad', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("It's Gonna Go Away", '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Wake Up', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Am I Going Crazy', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Hey Daddy', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Somebody Someone', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('No Way', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("Let's Get This Party Started", '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Wish You Could Be Me', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Coounting', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Dirty', '4');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Here To Stay', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Make Believe', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Blame', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Hollow Life', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Bottled Up Inside', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Thoughtless', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Hating', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('One More Time', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Alone I Break', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Embrace', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Beat It Upright', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Wake Up Hate', '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("I'm Hiding", '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("No One's There", '5');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Right Now', '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Break Some Off', '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Counting Of Me', '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Here It Comes Again', '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Deep Inside', '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Did My Time', '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("Everything I've Known", '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Play Me', '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Alive', '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("Let's Do This Now", '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("I'm Done", '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("Y'All Want A Single", '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('When Will This End', '6');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Twisted Transistor', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Politics', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Hypocrites', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Souvenir', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('10 or a 2-Way', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Throw Me Away', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Love Song', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Open Up', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Coming Undone', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Getting Up', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Liar', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('For No One', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Seen It All', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Tearjerker', '7');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Intro', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Starting Over', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Bitch We Got A Problem', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Evolution', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Hold On', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Kiss', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Do What They Say', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Ever Be', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Love And Luxury', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Innocent Bystander', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Killing', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Hushabye', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('I Will Protect You', '8');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Uber-Time', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Oildale', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Pop A Pill', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Fear Is A Place To Live', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Move On', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Lead The Parade', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Let The Guilt Go', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('The Past', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Never Around', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Are You Ready To Live?', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Holding All These Lies', '9');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Chaos Lives In Everything (feat. Skrillex)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Kill Mercy Within (feat. Noisia)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('My Wall (feat. Excision)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Narcissistic Cannibal (feat. Skrillex)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Illuminati (feat. Excision and Downlink)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Burn The Odedient (feat. Noisia)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Sanctuary (feat. Downlink)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("Let's Go (feat. Noisia)", '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Get Up! (feat. Skrillex)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Way Too Far (feat. 12th Planet and Flinch)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Bleeding Out (feat.Feed me)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Fuels The Comedy (feat. Kill The Noise)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Tension (feat. Excision, Datsik and Downlink)', '10');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Prey For Me', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Love & Meth', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('What We Do', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Spike In My Veins', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Mass Hysteria', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Paranoid And aroused', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Never Never', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Punishment Time', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Lullaby For A Sadist', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Victimized', '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("It's All Wrong", '11');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Insane', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Rotting In Vain', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Black Is The Soul', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('The Hating', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('A Different World', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Take Me', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Everything Falls Apart', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Die Yet Another Night', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("When You're Not There", '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Next In Line', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Please Come For Me', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Baby', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Calling Me Too Soon', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Out Of You', '12');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('The End Begins', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Cold', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ("You'll Never Find Me", '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('The Darkness Is Revealing', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Idiosyncrasy', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('The Seduction Of Indulgence', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Finally Free', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Can You Hear Me', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('The Ringmaster', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Gravity Of Discomfort', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('H@rd3r', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('This Loss', '13');
INSERT INTO titres (libelleTitre, idAlbum) VALUES ('Surrender To Failure', '13');